/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import snowflake.Snowflake;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Snowflake classUnderTest = new Snowflake();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
